name: Actualizar RPG Stats
on:
  schedule:
    - cron: '0 22 * * *' # Se ejecuta cada noche
  workflow_dispatch: # BotÃ³n manual

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar librerÃ­as
        run: pip install matplotlib numpy google-generativeai PyGithub

      - name: Ejecutar Script Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/rpg_stats.py

      - name: Guardar cambios
        run: |
          git config --global user.name "Gemini-Bot"
          git config --global user.email "bot@noreply.github.com"
          git add assets/rpg_stats.png
          git commit -m "ðŸ“Š Stats actualizados" || exit 0
          git push
